LICENSE
README.md
cage.c
meson.build
meson_options.txt
output.c
seat.c
seat.h
server.h
view.c
view.h
xdg_shell.c
xwayland.c
xwayland.h

With Cage becoming more popular since its mention on Phoronix and therefore getting more use-cases than just my own project, add XWayland support. The refactoring of 2cf40f7 makes this much easier. Note that this is a no-cost addition for those of us not using XWayland as it is a compile-time option that needs to be explicitly enabled by adding `-Dxwayland=true` to your meson command.

Add XWayland support

---

cage.c
seat.c
server.h
view.c
view.h
xdg_shell.c
xwayland.c

When using the Wayland or X11 backend, Cage is drawn inside a window. This commit sets this window's title to that of the currently focused toplevel window inside Cage.
Fixes #29.
I'm waiting with merging this until https://github.com/swaywm/wlroots/pull/1495 is in.

Set Cage's window title to toplevel's title

---

cage.c
output.c
seat.c
seat.h
view.c
view.h
xdg_shell.c
xdg_shell.h
xwayland.c
xwayland.h

This PR introduces a proper abstraction for views, with an interface and two implementations; one for XDG shell and another for XWayland. This cleans up some of the codebase, in my opinion, and makes it more extensible for [damage tracking](https://github.com/Hjdskes/cage/pull/31).
It also properly fixes our issue with XWayland surfaces during application startup.

Abstract views

---

view.c
xwayland.c

Override-redirect windows are meant to be ignored by the X server, at least as far as position goes. Hence, we detect whether we're dealing with such a window and consequently don't position it.
This makes, amongst others, Chromium's popup menus and dmenu appear on the correct position and size.

view: don't position override-redirect windows

---

cage.c
server.h
xdg_shell.c
xdg_shell.h

This commit adds a commandline switch (`-d`) to disable client side decorations, if possible. In this case, Cage will not draw any decorations of its own, in order to maximize screen real estate.
The default behavior remains the same, i.e., if `-d` is not passed, clients will draw their client side decorations, if any.
Fixes #32.

Implement xdg-decoration

---

cage.c

GTK still uses the (now deprecated) server-decoration protocol, which is the predecessor to xdg-decoration. Hence, with this commit Cage now also hides decorations on applications such as Firefox.
Fixes #47, see also https://github.com/Hjdskes/cage/pull/45#issuecomment-466402865.

Cage: implement server-decoration protocol

---

cage.c
output.c
seat.c
server.h

This commit adds two command line switches. -r rotates the output 90
degrees clockwise and can be specified multiple times. -f flips the
output.
Fixes #55

Implement output transform

---

.builds/alpine.yml
.builds/archlinux.yml
.builds/freebsd.yml
README.md
cage.c
meson.build
output.c

After [Drew's generous offer](https://github.com/Hjdskes/cage/pull/50#issuecomment-481702208), I hooked up a Sourcehut CI instead of Travis. Sourcehut solves the problem where we don't have access to hardware and are thus forced to use xvfb.
We're still using a rolling Arch image, but it is sufficiently easier compared to Travis. As a result, we now also build on Alpine *and* FreeBSD, so we get better coverage over different stacks as well (and compilers, since FreeBSD uses Clang). This has already resulted in two small fixes in Cage, as seen in this PR.
I have taken out the sanitizers for now, since I was running into issues inside mesa. For these I have opened a [bug report](https://bugs.freedesktop.org/show_bug.cgi?id=110479); once this is fixed I will look into adding the sanitizers …

Add Sourcehut CI builds

---

meson.build

Since we now have a tag with 0.1 and also a release with that version
number was published on GitHub we should adjust the version in the meson
file too.

Set version to 0.1

---

.builds/freebsd.yml

`/latest` has `epoll-shim.pc` after https://github.com/freebsd/freebsd-ports/commit/68b90c9df610ee3d99c719360256fcacf2e83603. Same as https://github.com/swaywm/wlroots/pull/1671.

Drop fixup_epoll in .builds/freebsd.yml

---

seat.c

seat: use XKB_* env vars for configuring keyboard devices

---

cage.c

This adds screencopy and xdg_output along with a silly mode switch where privileges are not dropped.

Assorted additions

---

cage.c

This fixes issue #89.
Per pull request #1915 for wlroots (https://github.com/swaywm/wlroots/pull/1915), these destructor functions can be removed as the resources will be destroyed with the wl_display by libwayland.

Removed destructors per wlroots PR 1915

---

cage.c
output.c
output.h
seat.c
server.h
view.c
xdg_shell.c

Outputs are arranged in a horizontal layout in the order they are
created in by wlroots. Maximized xdg_shell views will span all outputs,
like the global fullscreen mode in sway.
Fixes #87

Support multiple outputs

---

output.c

Following breaking changes in wlroots 0.9.0, `wlr_output_commit` must be
called after `wlr_output_set_mode`, `wlr_output_set_transform` and `wlr_output_enable`.
Additionally, `wlr_output_enable` is no longer implicitly called by
`wlr_output_set_mode`.
Fixes #102

Update new output handler for wlroots 0.9.0

---

LICENSE
meson.build
output.c
output.h
render.c
render.h
seat.c
util.c
util.h
view.c
view.h
xdg_shell.c
xwayland.c

This PR brings Cage's damage tracking and rendering code in line with what Sway is using. Previously, this code was based on tinywl. While it has worked for us up until here, it was kind of messy and hard to extend. I was working on adding layer-shell support but it was too difficult to add that into the old code.
Further, the Sway team knows what they're doing a lot better than I do, so I feel more comfortable using their code than my own. This change also makes it easy to keep up with what they're doing and to borrow more code from Sway.

Rewrite damage tracking & rendering code based on Sway's

---

.builds/alpine.yml
.builds/archlinux.yml
.builds/freebsd.yml

There are no breaking changes otherwise, so in meson.build we can leave
the version to anything greater than 0.9.1.

CI: build against wlroots 0.10.0

---

cage.c

Wayland requires this environment variable to be set, see
https://manpages.debian.org/experimental/libwayland-doc/wl_display_connect.3.en.html

Check if XDG_RUNTIME_DIR is set

---

output.c

Moved the include for xwayland.h into the if def block so it will build without X. It works on pure wayland but have not tested on a system with Xwayland.

move xwayland.h include to ifdef block for X11

---

seat.c
seat.h

Hi,
OK, so this is my first pull request, so bear with me ;).
Some time back, wlroots introduced the wlr_keyboard_group feature which groups multiple keyboards together to a single logical keyboard. This is useful since often a single physical keyboard may advertise itself as multiple keyboards which may lead to problems with compositor-defined keybindings. (e.g. if cage where to be run with a keyboard on which Alt and Escape were advertised on different keyboards, this would prevent the keybinding from working)
As of today, this is unlikely to concern  many people since the provided keybinding will be rarely used and it many cases Alt and Escape will be on the same keyboard. Nevertheless, I think that it is worth the extra code as it facilates the extension of cage with more keybindings …

Implement support for wlr_keyboard_group

---

seat.c

This fixes a bunch of invalid writes found with valgrind.

seat: remove signals earlier in seat destroy handler

---

view.c
xwayland.c
xwayland.h

Some apps like RetroArch will quit and fork itself to switch
modes (like from the menu to a loaded core). This means that for a
very short period of time we have no view available for Wayland. Right
now, Cage doesn’t actually exit when it does this terminate, so you
get this kind of zombie child process that is running but not showing
anything on the screen because there is no compositor.
The solution I have here is to just keep Cage’s Wayland server running
to avoid this issue. I’m open to other idea, but this seems sane to
me. Perhaps an alternative is to check if the process is still alive
when this happens, if not then we can do the quitting behavior. In
addition, we could make this an option if some users don’t want this
behavior.

Don’t terminate display when no view is found

---

cage.c

If setuid is called first then the target user may not have the ability to
setgid.
Refs: https://github.com/swaywm/sway/issues/4990

Cage: drop gid before uid

---

cage.1.scd
cage.c
output.c
server.h

This PR adds the option to have multiple behaviors for multi-output setups and adds one where only the last connected display is used, besides the (default) behavior of extending the display across all outputs. This mode is useful for e.g. handheld devices such as mobile phones who wish to attach to a larger monitor.

output: add option to use the last connected output only

---

meson.build
seat.c

This restores the original behaviour from 2cf40f7, is easier to read,
and satisfies clangformat.
This also doesn't call wlr_idle_notify_activity anymore, which was
probably unintended.

seat.c: Make clangformat happy and simplify the control flow

---

.builds/alpine.yml
.builds/archlinux.yml
.builds/freebsd.yml
cage.c
meson.build
output.c
output.h
render.c
seat.c
view.c
view.h
xdg_shell.c
xwayland.c

Tested via gtk3-demo and alacritty.
Fixes https://github.com/Hjdskes/cage/issues/171

Unbreak build with wlroots 0.13.0

---

seat.c

libxkbcommon will do it for us if we provide a NULL struct
xkb_rule_names.

Don't manually parse XKB_* env vars

---

seat.c

This fixes the drag icon not disappearing when releasing the
pointer button.
Reproduction steps:
- Open gedit
- Drag some text around
- Release the pointer button

Damage drag icon when destroyed

---

meson.build

This is handy when testing cage with a newer wlroots copy, or
when developing cage and wlroots patches in parallel.

build: allow using subproject for wlroots

---

xdg_shell.c

Certain clients (like Chromium in Kiosk mode) don't like figuring out their own window geometry if they display in fullscreen mode. Since setting this is very easy for cage, let's give them the correct geometry instead implicitly passing (0, 0) and letting them figure it out.
Not sure if reaching this deep into xdg_shell_view is a good idea, but I couldn't find a closer reference which would give access to the output layout.

Set xdg_toplevel geometry for fullscreen clients

---

meson.build

Previously, the output of `meson build` would warn about the use of some functions that have been deprecated since meson v0.56.0, and the use of the `check` kwarg in the `run_command()` function. Update meson.build to fix these build warnings.
[meson-build-log.txt](https://github.com/Hjdskes/cage/files/9149415/meson-build-log.txt)

Fix warnings in `meson build' output for deprecated functions.

---

README.md

cage currently uses GitHub CI, not SourceHut.

readme: drop CI badge

---

cage.c
seat.c
seat.h
server.h

Successor to #189. Fixed conflicts and updated.
Fixes #21 
Fixes #133 
Tested with:
`WLR_BACKENDS=headless WLR_NO_HARDWARE_CURSORS=1 WLR_LIBINPUT_NO_DEVICES=1 WLR_HEADLESS_OUTPUTS=1 ./cage`

Virtual input

---

cage.1.scd
cage.c
output.c
output.h
server.h
view.c
view.h

I have tried to resume work from @dimkr in PR #213.
- Rebased on current HEAD
- Implements output manager test (`wlr-randr --dryrun`)
- Add output layout change monitor to ensure views are well positioned according to new layout
For the moment, I have only played with Wayland as backend.
I am still unsure about `current_mode` test, see [discussion](https://github.com/cage-kiosk/cage/pull/213#discussion_r1267768236).
Furthermore, trying to disable an output returns an error. I don't know if it specific to Wayland backend. Here are the logs from wlroots (0.16.2):
```
00:00:04.247 [types/output/output.c:656] Tried to modeset a disabled output
00:00:04.247 [types/output/output.c:734] Basic output test failed for WL-2
```

Add basic wlr-output-management support 

---

seat.c
seat.h

wl_touch::frame() is expected to be sent to client to indicate end of touch frame event and not sending it may causes issues. For example, Qt applications using Qt Wayland platform plugin do not consider touch events until this end of frame event to be received.

seat: add missing touch_frame handler

---

output.c

Only terminate if the last output was nested under the Wayland or X11 backend. If not, using DRM backend for example, terminating Cage when unplugging the last monitor or simply turning it off does not seem to be the right behavior.
Proposed as a draft for now.
It addresses issue #208 .

output: do not always terminate when last output is destroyed

---

cage.c
seat.c
seat.h
server.h

It should fix issue #286 as relative-pointer-unstable-v1 seems mandatory for RetroArch.
Once again, the code is inspired from Sway. I have added two minor extra commits which can me dropped if needed.
@vanfanel, it would be nice if you could give this branch a try with RetroArch.

Add relative-pointer-unstable-v1 support

---

.github/workflows/main.yml

Other jobs are canceled when one of the compile jobs fails.
This allows you to check how other things succeed or fail.
Reference: https://github.com/actions/runner/issues/2347

CI: Continue other jobs even if one job fails

---

.github/workflows/main.yml
cage.c
idle_inhibit_v1.c
meson.build
meson_options.txt
output.c
output.h
seat.c
server.h
xdg_shell.c
xwayland.c
xwayland.h

Makes cage build against wlroots master. We are still lacking an output request_state handler though.

wlroots 0.17

---

xwayland.c

When destroying an xwayland surface, the dissociate and destroy handlers are called, but both of these were removing the map and unmap signal handlers, causing a segfault when the destroy handler went to remove them.
Fixes #309

xwayland: fix double wl_list_remove

---

output.c

wlr_scene_output_layout_add_output() aborts when called with an already-added output.
To reproduce, run wlr-randr to reconfigure one of the enabled outputs.
cc @kennylevinsen

output: fix assert when re-adding output to layout

---

.github/workflows/main.yml
README.md
meson.build
meson_options.txt

This is unnecessary because Xwayland logic doesn't bring in new dependencies. We can just compile in our Xwayland-related code when wlroots has been built with Xwayland support.
See this Sway patch: https://github.com/swaywm/sway/pull/8165

build: drop xwayland option

---

.github/workflows/main.yml

Catches mistakes such as non-existing build options.

ci: turn on --fatal-meson-warnings

---

cage.c

server.wl_display is already a pointer.
Reported-by: Jonathan GUILLOT <jonathan@joggee.fr>

cage: fix SIGINT/SIGTERM handler data

---

.github/workflows/main.yml
README.md
cage.c
meson.build
output.c
seat.c
server.h
view.c
xdg_shell.c
xdg_shell.h

Upstream breaking changes: https://gitlab.freedesktop.org/wlroots/wlroots/-/releases/0.18.0
TODO:
- Check out wlroots 0.18 branch in CI
- Fix the following:
```
00:00:00.168 [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface
```
- Fix the following on exit:
```
cage: ../wayland-1.22.0/src/wayland-server.c:1483: wl_display_terminate: Assertion `ret >= 0 || errno == EAGAIN' failed.
```

Add support for wlroots v0.18

---

README.md

Mentioned here https://github.com/cage-kiosk/cage/issues/367#issuecomment-2440883941
Currently it is possible to view the man pages either through installing them or by finding the correct file in the project. This PR links the man pages directly in the root README.

readme: Link man pages in root README

---

cage.1.scd
cage.c
server.h

For bug reports, it's useful to ask for a debug log. However there's no way for users to enable debug logs without recompiling. Add a CLI flag to do so.

Add CLI flag to enable debug logs

---

output.c

This is dropped in the next wlroots release.

output: drop unused wlr_matrix.h include

---

cage.c
xdg_shell.c

v5 adds the wm_capabilities event. cage only supports fullscreen.

xdg_shell: bump to v5
