- seat.c
- seat.h
> Add touch input

- cage.c
- idle_inhibit_v1.c
- idle_inhibit_v1.h
- meson.build
- seat.c
- server.h
Note that this does not do much without an idle manager "on the other side". See, for example, swayidle: https://github.com/swaywm/sway/blob/master/swayidle/swayidle.1.scd
Fixes #7
> Add idle tracking

- view.c
This is to work around "misbehaving" (for lack of a better term) clients. At the moment, Firefox Nightly and Google Chrome/Chromium are known to be suchs client:
When XWayland support is enabled, Firefox first creates an XWayland surface, closes this (before mapping it) and then opens an XDG toplevel surface. Cage tries to manage the first XWayland surface, but when it closes, Cage has no surfaces left and hence closes as well.
Hence, Cage terminates before it picks up on Firefox's XDG toplevel, and Firefox (rightly) prints it cannot read the Wayland pipe.
In Chromium's case, it simply opens an XWayland surface which it immediately closes, before opening the "real" XWayland surface.
The workaround is to track whether an XWayland surface has been mapped and, if it hasn't, to not exit when …
> view: test whether XWayland surfaces have been mapped

- cage.c
- meson.build
- output.c
- output.h
- seat.c
- server.h
- view.c
- view.h
- xdg_shell.c
- xdg_shell.h
- xwayland.c
- xwayland.h
From my (limited) testing this seems to be working, but I'd appreciate any input from others on how it works for them. Any glances over the code are also appreciated!
> Implement damage tracking

- xdg_shell.c
- xdg_shell.h
- xwayland.c
- xwayland.h
> Listen to fullscreen requests

- seat.c
- seat.h
These commits make Cage work with the [breaking changes](https://github.com/swaywm/wlroots/releases/tag/0.3) of wlroots 0.3.
> Update to wlroots 0.3

- output.c
> Wrap x11 backend features in wlroots' feature flag

- .builds/alpine.yml
- .builds/archlinux.yml
- .builds/freebsd.yml
- output.c
- xdg_shell.c
(which is presently unreleased)
> Updates for wlroots 0.6.0

- .builds/alpine.yml
- .builds/archlinux.yml
See https://github.com/swaywm/wlroots/issues/1796
> CI: use a version of wlroots that compiles with libinput 1.14

- output.c
> Set startup color to black.

- cage.c
> Implement wlr-gamma-control-unstable-v1

- docs/env_vars.md
> Document environment variables

- cage.c
> Implement wlr_export_dmabuf_unstable_v1

- .builds/alpine.yml
- .builds/archlinux.yml
- .builds/freebsd.yml
- meson.build
- output.c
I missed this one in the previous PR.
> output: call wlr_output_rollback if not rendering

- output.c
> output: add support for direct scan-out

- seat.c
This should make it easier to troubleshoot why, for example, a touch input device isn't mapped to a touch output device. See #126.
> seat: log around input device mapping

- .builds/alpine.yml
- .builds/archlinux.yml
- .builds/freebsd.yml
- README.md
- cage.1.scd
- meson.build
- meson_options.txt
Here's my initial attempt for a man page. I will clean up and fix things later on, of course.
Fixes #137
> Add man page.

- cage.c
- seat.c
- server.h
Code that does the VT switch taken from sway.
> Add option to allow changing VT

- .builds/alpine.yml
- .builds/archlinux.yml
- .builds/freebsd.yml
- cage.c
- meson.build
- output.c
This PR cherry-picks @jbeich's commits from #143 and adds one new breaking change added to wlroots since. Thanks @jbeich!
> Unbreak build with wlroots 0.11.0

- output.c
@emersion - maybe this loop should be moved to wlroots, something like `wlr_output_set_any_mode()` or `wlr_output_set_mode_auto()`
> Fall back to a lower output mode if needed (swaywm/sway@4cdc4ac63)

- cage.c
Based on https://github.com/swaywm/sway/pull/6516
> Allow running as root when not using setuid bit

- .github/workflows/main.yml
- cage.c
- meson.build
- output.c
- seat.c
- seat.h
- view.c
- view.h
- xdg_shell.c
- xdg_shell.h
There shouldn't be any more breaking changes this release upstream.
> Port to wlroots 0.16

- cage.c
Closes: https://github.com/cage-kiosk/cage/issues/255
> Log execvp() failures

- README.md
> Establish chain of trust for signed releases

- output.c
The output is disabled then re-enabled using the wlr-output-management protocol with tool such as wlr-randr.
```
$ wlr-randr --output HDMI-A-1 --off
$ wlr-randr --output HDMI-A-1 --on
```
When re-enabled the new output configuration is committed before the output to be added to the global output layout. However, `handle_output_commit()` expects the output to be already part of this global layout and assert failed. Now, do not treat this in `handle_output_commit()` and simply ensure the resulting scene output is not NULL in `handle_output_frame()`.
> output: fix crash when re-enabling DRM output

- cage.c
- seat.c
wlroots 0.19 will abort if dangling listeners are left behind.
> Ensure all listeners are removed on shutdown
